### ISSUE TITLE
Chest Networks - Sorting

### ISSUE THREAD

**Issue by Nacholebraa** [MinecraftCitiesNetwork/Bugs#13]
User: aligoth / homelessbum

Issue: _I was messing with networks with homelessbum, I added them to my network, gave them the sorting chest, and the filter wand to show them how it works...they placed it, learned how it works, and then tried to break the chest to give it back. They couldn't because it said they weren't part of the network. I again, did /net user add HomelessBum, and it told me they are already part of the network, and still wouldn't let them break the chest_

**Comment by Nacholebraa** [comment]
User: aligoth

Additional Issue Points: _sorting networks only function when the input chest is opened...is that intentional or a bug? so, i'm trying to use it in my farm to automate sorting goods that drop into respective chests....but it only sorts when I open the input chest. the problem there is that if I dont go aroudn and open all the chests periodically, the system clogs :(_

**Comment by Technofied** [comment]
I've forwarded this to the developer for their take.

**Comment by Kwantux** [comment]
> Issue: _I was messing with networks with homelessbum, I added them to my network, gave them the sorting chest, and the filter wand to show them how it works...they placed it, learned how it works, and then tried to break the chest to give it back. They couldn't because it said they weren't part of the network. I again, did /net user add HomelessBum, and it told me they are already part of the network, and still wouldn't let them break the chest_

So if I understood it right, they can add chests to the network, but not break them once placed?
Can you check if `/net info` shows their name under users?



> Additional Issue Points: _sorting networks only function when the input chest is opened...is that intentional or a bug? so, i'm trying to use it in my farm to automate sorting goods that drop into respective chests....but it only sorts when I open the input chest. the problem there is that if I dont go aroudn and open all the chests periodically, the system clogs :(_

This is intentional. Periodic checks would massively draw performance.
However any vanilla way of transmitting items into a chest should be covered, so if you pipe items into an input container via a hopper, it should instead directly be sorted into the network. If you use input hoppers, all collected items automatically go into the network.

I did find the issue here though.
Double chest input containers consist of only one actual network component and one vanilla chest. When items are piped into the vanilla half, it doesn't automatically sort, which is a bug.
I will fix this later, thanks for reporting.

**Comment by Kwantux** [comment]
Both bugs should be fixed now, update is out on Modrinth and Hangar now

**Comment by Technofied** [comment]
> Both bugs should be fixed now, update is out on Modrinth and Hangar now

Much appreciated!
